name: Deploy to Test
on:
  workflow_dispatch:

jobs:
  Checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Venv
        run: pip install virtualenv
      - name: Activate Venv
        run: virtualenv venv
      - run: source venv/bin/activate
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Isort
        run: pip install isort
      - run: isort ${{ github.workspace }}
      - name: Black
        run: pip install black
      - run: black ${{ github.workspace }}
      - name: Pyright
        run: pip install pyright
      - run: pyright ${{ github.workspace }}
  deploy:
    needs: Checks
    runs-on: ubuntu-22.04
    environment: Test
    env:
      API_KEY: ${{ secrets.API_KEY }}
      DEPLOY_CURL_COMMAND: 'curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer $API_KEY" --data {\"signal\":\"restart\"} https://control.sparkedhost.us/api/client/servers/812ca87d/power'
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update packages
        run: sudo apt-get update -qy
      - name: install lftp
        run: sudo apt-get install -y lftp curl
      - name: restart shell
        run: exec $shell
      - name: perform FTP Upload
        run: lftp -e "debug; set sftp:auto-confirm yes; set ssl:verify-certificate false; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -X .* -X .*/ -X venv/ -X resources/ --reverse --verbose --delete; bye"
      - name: Reboot server
        run: eval "$DEPLOY_CURL_COMMAND"
