name: Deploy to Prod
on:
  workflow_dispatch:

jobs:
  quality_checks:
    uses: ./.github/workflows/quality_checks.yml
  deploy:
    needs: quality_checks
    runs-on: ubuntu-22.04
    environment: Prod
    env:
      API_KEY: ${{ secrets.API_KEY }}
      DEPLOY_CURL_COMMAND: 'curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Authorization: Bearer $API_KEY" --data {\"signal\":\"restart\"} https://control.sparkedhost.us/api/client/servers/2748842e/power'
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_HOST: ${{ secrets.FTP_HOST }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: update packages
        run: sudo apt-get update -qy
      - name: install lftp
        run: sudo apt-get install -y lftp curl
      - name: restart shell
        run: exec $shell
      - name: perform FTP Upload
        run: lftp -e "debug; set sftp:auto-confirm yes; set ssl:verify-certificate false; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -X .* -X .*/ -X venv/ -X resources/ --reverse --verbose --delete; bye"
      - name: Reboot server
        run: eval "$DEPLOY_CURL_COMMAND"
